[tool.poetry]
name = "pycoin"
version = "0.1.0"
description = "A cryptocurrency library."

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
dev-1 = "dev-package-1"
dev-2 = "dev-package-2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"