[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.5.0"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.10"

[tool.setuptools_scm]
local_scheme = "no-local-version"
